server:
    error:
        include-stacktrace: on_param
spring:
    datasource:
        url: jdbc:mysql://localhost:3307/anime?usesSL=false&createDatabaseIfNotExists=true
        username: root
        password: root
    jpa:
        hibernate:
    ddl-auto: update